#+ summary: select the equivalent URIs for a uniprot entry from bioregistry SPARQL endpoing
#+ endpoint: https://bioregistry.io/sparql
#+ tags: 
#+   - identifiers
#+ defaults:
#+   - input_iri: http://identifiers.org/uniprot/P01308
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?input_iri ?mapped_uri
{
    
    ?_input owl:sameAs ?mapped_uri.
}
