#+ summary: select the equivalent URIs for a uniprot entry from bioregistry SPARQL endpoing
#+ endpoint: https://bioregistry.io/sparql
#+ tags: 
#+   - identifiers

SELECT DISTINCT ?input_iri ?mapped_uri
{
    VALUES ?input_iri { 
        <http://identifiers.org/uniprot/P01308>
    }  
    ?input_iri owl:sameAs ?mapped_uri.
}
